from .awal_handler import *
from .tambah_admin import *
from .send_handler import * 
from .ban_handler import *
from .bot_handler import *
from .talent_handler import *
from .daddy_sugar import *
from .moans_girl import *
from .moans_boy import *
from .boyfriend_rent import *
from .girlfriend_rent import *
from .broadcast_handler import *
